# Project Information
site_name: Portfolio
site_url: https://immve.github.io/portfolio/
site_author: IMM
site_description: >-
  Personal portfolio

# Repository
repo_name: immve/portfolio
repo_url: https://github.com/immve/portfolio

# Copyright
copyright: Copyright &copy; 2021 - 2023

# Configuration
theme: 
  name: material
  custom_dir: overrides
  palette: 
    - scheme: default
      primary: green
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  
nav:
  - Home: index.md
  - Page 1: page1.md
  - Page 2: page2.md
extra_css:
  - assets/styles/custom.css

# Extensions

markdown_extensions:
  - admonition
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: immve
      repo: portfolio